facebank_dir: "facebank"
facebank_output: "models/weights/facebank/facebank.pkl"

# mediamtx server fill with 'null' if you dont need previews
rtsp_server_host: "rtsp://admin:PWD@192.168.0.102:8554/Streaming/Channels"

# Please follow this format to add a new sources:
# name_of_cctv : [
#   cctv_url,
#   null, #fill with null
#   Show preview (if True, rtsp_server_host can't be null) (True/False)
# ]

# insert below

sources: {
  # tes_main_in: [
  #   0,
  #   null, #ROI
  #   True, #show previes
  #   True # take new data
  # ],
  tes_maincam_out: [
    0,
    null,
    True
  ],
  cctv_maincam_out: [
    "rtsp://admin:PASSW@192.168.0.133/Streaming/Channels/101",
    null,
    True
  ]
}

num_detectors: 4 #how many detector workers will be used 

sql_config: {
  host: "localhost",
  database: "cctv_db",
  user: "username",
  password: "password",
  table: "cctv_logs"
}
