facebank_dir: "facebank"
facebank_output: "models/weights/facebank/facebank.pkl"

rtsp_server_host: "rtsp://admin:PWD@192.168.0.102:8554/Streaming/Channels"

sources: {
  # tes_main_in: [
  #   0,
  #   null, #ROI
  #   True, #show previes
  #   True # take new data
  # ],
  tes_maincam_out: [
    0,
    null,
    True,
    True
  ],
  cctv_maincam_out: [
    "rtsp://admin:PASSW@192.168.0.133/Streaming/Channels/101",
    null,
    True,
    True
  ]
}

num_detectors: 4

sql_config: {
  host: "localhost",
  database: "cctv_db",
  user: "username",
  password: "password",
  table: "cctv_logs"
}